// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	model "ad-server-project/src/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RewardDetailRepository is an autogenerated mock type for the RewardDetailRepository type
type RewardDetailRepository struct {
	mock.Mock
}

// DeductRewardDetail provides a mock function with given fields: c, reward, userId, rewardType
func (_m *RewardDetailRepository) DeductRewardDetail(c context.Context, reward int, userId int, rewardType string) error {
	ret := _m.Called(c, reward, userId, rewardType)

	if len(ret) == 0 {
		panic("no return value specified for DeductRewardDetail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) error); ok {
		r0 = rf(c, reward, userId, rewardType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EarnRewardDetail provides a mock function with given fields: c, adId, reward, userId, rewardType
func (_m *RewardDetailRepository) EarnRewardDetail(c context.Context, adId int, reward int, userId int, rewardType string) error {
	ret := _m.Called(c, adId, reward, userId, rewardType)

	if len(ret) == 0 {
		panic("no return value specified for EarnRewardDetail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, string) error); ok {
		r0 = rf(c, adId, reward, userId, rewardType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllRewardDetail provides a mock function with given fields: c, userId
func (_m *RewardDetailRepository) GetAllRewardDetail(c context.Context, userId int) ([]model.RewardDetail, error) {
	ret := _m.Called(c, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRewardDetail")
	}

	var r0 []model.RewardDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.RewardDetail, error)); ok {
		return rf(c, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.RewardDetail); ok {
		r0 = rf(c, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RewardDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(c, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecent provides a mock function with given fields: c, userId
func (_m *RewardDetailRepository) GetRecent(c context.Context, userId int) ([]model.RewardDetail, error) {
	ret := _m.Called(c, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetRecent")
	}

	var r0 []model.RewardDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.RewardDetail, error)); ok {
		return rf(c, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.RewardDetail); ok {
		r0 = rf(c, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RewardDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(c, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRewardDetailRepository creates a new instance of RewardDetailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRewardDetailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RewardDetailRepository {
	mock := &RewardDetailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
